language: node_js
addons:
  apt:
    packages:
      - gdal-bin
services:
  - postgresql
before_script:
  - psql -c 'create database binsmap;' -U postgres
  - psql -U postgres -c "create extension postgis"
script:
  - ./1-getbins.sh
  - ./2-loadbins.sh
  - ./3-mergebins.sh
  - ./4-dumpbins.sh

